### ISSUE TITLE
How should GUI display hashes?

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#100]
At the moment outputs are displayed as raw tuples of `(name, hash)` - this should be improved (with hover-over?)

**Comment by jvdzwaan** [comment]
You are either interested in runs from the same script that produced the exact same files or different files. Perhaps we should add tabs (or something else that can show or hide information on a website) for listing runs generated by the same script with the same hash for the output file and listing runs generated by the same script with a different hash.

And some functionality that somehow compares two runs would be also useful, I think

**Comment by robintw** [comment]
I think the way we're displaying hashes works well at the moment, particularly as you can click on a hash to search for it - so I'm going to close this and we can reopen if we run into problems with the way they are displayed.
