### ISSUE TITLE
Log user defined values

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#104]
Allow users to store custom information in runs, something like recipy.logValue(name, value)

The use case is workflow engine noodles https://github.com/NLeSC/noodles where we want to keep track of which function/process/machine created a result.

But it is also useful when working with multiple people on the same project.

This could be a way of solving #48, although it is not effortless.

**Comment by robintw** [comment]
What do you think is the best way to deal with this? Should have a `custom-values` key in the data for a run and then store as a set of key-value pairs within that?

**Comment by jvdzwaan** [comment]
Yes, seems like a reasonable approach!

**Comment by robintw** [comment]
This should be pretty easy to implement, if one of the 'newbies' from the PyConUK sprint want to have a go at it? @trbedwards @DavidS48 @BevelledEdge

**Comment by trbedwards** [comment]
I'll have a go at this
