### ISSUE TITLE
Store data diffs

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#107]
Store diffs of output files.

**Comment by bilderbuchi** [comment]
If you store the output files themselves, what's the added value of storing the diffs, too, instead of generating them on demand?

**Comment by jvdzwaan** [comment]
If you use the same output files for multiple runs, they get overwritten. Also I think storing diffs is more efficient than storing complete outputs. Like #95, but storing more elaborate information.

**Comment by bilderbuchi** [comment]
ah I see.

**Comment by robintw** [comment]
This is implemented now (albeit with a Py2/3 issue - #121).
