### ISSUE TITLE
Warn if recipy is not the first module to be imported

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#108]

**Comment by robintw** [comment]
This should be reasonably easy to do by checking `sys.modules` in recipy's `log_init` function, and raising a warning if there are things in there that we don't expect.

**Comment by robintw** [comment]
This seems to be done, and seems to be working for me. Ok to close @jvdzwaan?

**Comment by jvdzwaan** [comment]
Yes, but the solution is kind of hacky (also see #119). 

Closing this one, because the problem is logging warnings, not issuing warnings
