### ISSUE TITLE
TypeError: 'Query' object is not callable when searching for runs in GUI

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#112]
Or simply 'internal server error' if gui is run in normal (no debug) mode.

**Comment by jvdzwaan** [comment]
It seems this issue is caused by a change in tinydb (contains was renamed to search): https://github.com/msiemens/tinydb/issues/93

**Comment by robintw** [comment]
Ah yes, there have been various changes to TinyDB that broke various things in the command-line code, but I probably didn't check the GUI code properly...sorry!

**Comment by jvdzwaan** [comment]
That's why we need tests :)
