### ISSUE TITLE
Use with R via doit?

### ISSUE THREAD

**Issue by docsteveharris** [recipy/recipy#114]
Lovely concept and implementation. Thanks.

Is it possible to use this with R?

I assume not directly? But what would happen if you used [doit](http://pydoit.org/contents.html) and wrote `import recipy` at the top of your doit file?

**Comment by robintw** [comment]
Unfortunately recipy doesn't support R, and is unlikely to do so in the near future.

Having looked in to `doit`, that won't help it work with R either - sorry!
