### ISSUE TITLE
Split the GUI into a separate PyPI package?

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#117]
Some feedback I got from CW16 was that recipy seems to have a **lot** of dependencies. Many of these come from the GUI (Flask and all of its dependencies) - so it might be an idea to split the GUI into a separate package, so that those who don't want it don't have to install it?

**Comment by jvdzwaan** [comment]
To be honest, I don't really see the point, it's not like you have to install gigabytes of stuff. However, if you think it is better, I won't object. 

Actually my main concern is that we'll end up in some kind of dependency hell (well, a light version of it ;) How do we make sure the gui remains compatible with the main recipy module?

**Comment by robintw** [comment]
To be honest, I kinda agree with you - I don't have a problem with installing dependencies, but some people are quite picky about dependencies :P

I think it would be possible to do it without having dependency hell (IPython etc manage it with their various split-up packages), but it might make life more complicated.

I'll mark this as a 'long-term' possible idea - I have no huge feelings one way or the other

**Comment by jvdzwaan** [comment]
Long-term idea it is :)

Let's see if people respond to this discussion.

**Comment by robintw** [comment]
I think this is probably not a great plan for the moment - closing until it becomes an issue.
