### ISSUE TITLE
latest_run throws an error if there are no runs in the database

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#118]
A test should be added for this as well.

**Comment by robintw** [comment]
Fixed in f94733e882bae395d4bbacab9d25791612ad0cf6

**Comment by jvdzwaan** [comment]
Must still be fixed in the gui (I'll do it)

**Comment by robintw** [comment]
Oops, I thought they used the same underlying function - sorry!

**Comment by jvdzwaan** [comment]
Well maybe they should use the same underlying function :)
