### ISSUE TITLE
CITATION file need

### ISSUE THREAD

**Issue by rgaiacs** [recipy/recipy#182]
Could you provide a [CITATION file](https://www.software.ac.uk/blog/2016-10-06-encouraging-citation-software-introducing-citation-files)?

**Comment by jspaaks** [comment]
I've made a PR (https://github.com/recipy/recipy/pull/190) that uses ``CITATION.cff`` instead of ``CITATION``. More info here: https://software.ac.uk/blog/2017-12-12-standard-format-citation-files

**Comment by robintw** [comment]
Thanks both, this is now done.
