### ISSUE TITLE
Inputs logged multiple times using different libraries

### ISSUE THREAD

**Issue by jvdzwaan** [recipy/recipy#184]
I'm working on adding support for logging netcdf-files and made a patch for the [netCDF4](https://github.com/Unidata/netcdf4-python) library (see `netcdf` branch if you are interested). Next on my list of libraries to patch was xarray, and I quickly found out that xarray uses netCDF4 to read (and presumably write) netcdf files. This means that recipy logs the input two times: once with xarray and once with netCDF4.

Output from console (with debug on):

```
Patching xarray
Patching input function: open_dataset
Input from ('/home/jvdzwaan/code/recipy/integration_test/packages/data/netcdf4/testrh.nc', '3972c0cb483ab5dfb95716d48fbf9d5881e9c125') using xarray
Patching netCDF4
Patching input/output function: Dataset
Input from ('/home/jvdzwaan/code/recipy/integration_test/packages/data/netcdf4/testrh.nc', '3972c0cb483ab5dfb95716d48fbf9d5881e9c125') using netCDF4
```

I guess we want to show these two entries as a single input for the run, but keep the information about the multiple libraries/versions (so in this case both `xarray v0.10.8`, and `netCDF4 v1.4.0`). Any other thoughts?

refs #176

**Comment by robintw** [comment]
This should be complete when #189 is merged.
