### ISSUE TITLE
Store hash for input/output files

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#25]
Possibly...

**Comment by robintw** [comment]
Basically the same as #41

**Comment by robintw** [comment]
A number of questions here:

1. What hash function should we use?

2. How do we know when the output files have finished being written to, so that we can calculate the hash? It'd be great to register a function to run when Python exits...but I'm not sure how that is possible, and whether it would cause problems (eg. if Python crashes)

3. Do we do this by default? Or require users to 'opt-in'? Or just do it for files less than a certain size? (The latter could be based upon how long it takes to calculate a hash...?)

4. We could have a separate recipy command (`recipy hash`) which hashes the file in the most recent recipy run...but that requires a manual step. It'd be easier to implement than the issues discussed in (3) above though.

**Comment by robintw** [comment]
Probably easiest to try first of all is to just put it straight after calling the function in `log_output` (and `log_input` possibly?) and see how well it works - it'd need to be done on a branch to begin with and tested thoroughly!

**Comment by kynan** [comment]
For registering a function to be run at interpreter termination you could use [atexit](https://docs.python.org/2/library/atexit.html).

**Comment by jni** [comment]
@robintw, @kynan's suggestion seems perfect!

With regards to the hash function, I would suggest using whatever git uses, which I'll admit I know nothing about.

**Comment by jni** [comment]
More importantly, when do we sprint on this??? =)

**Comment by kynan** [comment]
Git uses SHA1.

**Comment by elisabethzues** [comment]
I think a separate command would be fine at first and depending on how useful other people would find it it could always be integrated later?
I use md5sum but using the same algorithm as git seems like a good idea.

**Comment by bilderbuchi** [comment]
I think this would be a very useful/essential addition. Think about some data analysis workflow: you load some file, do some processing/tweaking, and store an output file/image. You look at the image, tweak the plot, add some more data to the plot, rinse and repeat a couple of times. 
Recipy stores every run, but your output filename typically stays constant. This means that, looking at the output file a couple months later, you will probably not be able to identify the specific run associated with that output file. If you store the output file's hash, it will be possible to identify the run that created it.

**Comment by bilderbuchi** [comment]
Btw, I just found out that Git uses _not only_ the file contents for the hash computation, see [this SO answer](http://stackoverflow.com/a/24283352). But yeah, plain SHA-1 sounds like a reasonable default.

**Comment by robintw** [comment]
This has now been implemented.
