### ISSUE TITLE
Logging of parameters

### ISSUE THREAD

**Issue by elisabethzues** [recipy/recipy#40]
One key feature would be to log parameters as well (both command line parameters as well as hardcoded ones). Would be great to have this.

**Comment by robintw** [comment]
Hardcoded parameters should be recorded automatically by the `git diff` storage - although we could potentially add a decorator or something to store your parameters explicity.

For command-line parameters, we can definitely store `sys.argv`.

I'll close this issue and create two separate issues for the two bits above, as I think one will be far easier/quicker than the other!
