### ISSUE TITLE
Hook into standard `open` etc in pure python

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#44]
So we can log things like:

    with open('blah.txt', 'r') as f:
        f.readlines()

**Comment by robintw** [comment]
I've started making an attempt at this, and it's more complicated than I realised.

Actually hooking `open` is relatively simple. Adding the following code to `__init__.py` will do it:

```python
# Patch built-in open function
orig_open = __builtins__['open']
def patched_open(*args, **kwargs):
	print('Called open!')
	print(args)
	print(kwargs)
	return(orig_open(*args, **kwargs))

__builtins__['open'] = patched_open
```

However, the problem is that _loads_ of things in Python use the `open` function internally, and we don't want to hook those, we only want to hook when the user uses `open` explicitly themselves. For example, using the code above we get all of the times `open` is used internally by recipy (for checking `.git` folders, for opening the recipy database file etc), and all of the times it is used internally by any other modules.

It is possible to find out the calling function of a called function - so we could find out where `open` was called from (see http://stackoverflow.com/questions/2654113/python-how-to-get-the-callers-method-name-in-the-called-method), but I suspect that will be fairly computationally inefficient.

Does anyone have any ideas how we could progress with this? (@jvdzwaan? Anyone else?)

**Comment by jvdzwaan** [comment]
An alternative would be to create a recipy.open (or something like that) that is patched. The disadvantage being of course that tracking isn't effortless any more...

Would it be possible to warn the user he doesn't use the patched version of open if he doesn't import it from recipy?

**Comment by ritviksahajpal** [comment]
Does this mean that if some library is using pandas internally (df.to_csv), and we use recipy, then recipy will log the to_csv from that library as well?

**Comment by robintw** [comment]
@ritviksahajpal Yes, it will.

**Comment by robintw** [comment]
I think this has been implemented now by @jvdzwaan.
