### ISSUE TITLE
Configuration file should be ~/.recipy/recipyrc

### ISSUE THREAD

**Issue by kynan** [recipy/recipy#46]
Since the configuration is already in a "hidden" folder there is no need to have it be a "hidden" file.

**Comment by robintw** [comment]
Thanks, I realised that in the middle of my talk!

**Comment by robintw** [comment]
Fixed in a2e1cf39bb65e68569685c72138c84e3b8cbe153

I've made it so that `.recipyrc` still works for config files in the current directory (so you can have project-specific configs), but it is `recipyrc` when inside the `~/.recipy` directory.
