### ISSUE TITLE
Add export option to the GUI

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#68]
Some sort of button or link on the details page that gives you the JSON (ideally pretty-printed) for that record would be great

**Comment by jvdzwaan** [comment]
http://code.runnable.com/UiIdhKohv5JQAAB6/how-to-download-a-file-generated-on-the-fly-in-flask-for-python
http://stackoverflow.com/questions/12943819/how-to-python-prettyprint-a-json-file
