### ISSUE TITLE
No module named recipy.__main__; 'recipy' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by re4lfl0w** [recipy/recipy#77]
```python
# a.py
print('Hello World')

with open('1.txt', 'a') as f:
    f.write('aa')
```

```bash
(general)tmp $ python -m recipy SCRIPT a.py
```

```bash
tmp $ python --version
Python 2.7.10
```

```
Run 2aa3938b-aae2-4c81-b4da-907c57c25ab1
Date	2015/09/05 15:10
Author	re4lfl0w
Command	~/.virtualenvs/general/bin/python
Script	/private/tmp/a.py
Inputs	none
Outputs	none
Environment	~~~~~
```

recipy run inserted, with ID 10c84143-4f89-40fb-9fe9-aee3a3dac427
~/.virtualenvs/general/bin/python: No module named recipy.__main__; 'recipy' is a package and cannot be directly executed

**Comment by robintw** [comment]
Thanks for reporting this, we'll look into it. I suspect it is a Python 2 vs Python 3 thing - if you have access to Python 3 then it might work better there.

@kynan Do you have any ideas what's causing this, and how it might be able to be fixed?

**Comment by re4lfl0w** [comment]
Same error in python3

```bash
(python3) tmp $ python --version
Python 3.4.3
```

```bash
tmp $ python -m recipy SCRIPT a.py
recipy run inserted, with ID 55101e3e-3ef7-4d60-a18c-73a4dafa0f38
~/.virtualenvs/python3/bin/python: No module named recipy.__main__; 'recipy' is a package and cannot be directly executed
```

**Comment by robintw** [comment]
Ah, I think I've realised the problem: you don't need the verbatim `SCRIPT` in your command, that should be replaced by the actual name of the script. For example:

`python -m recipy a.py`

That works for me, does it work for you?

**Comment by robintw** [comment]
Actually, also - are you using the latest version from Github, or have you installed via `pip`? If you've installed from `pip` then that version doesn't have this functionality yet. A new version will be released in a few days that does though - sorry for the delay!

**Comment by kynan** [comment]
@robintw Yes, sounds like @re4lfl0w is using an old version which doesn't have the `__main__` package entry point yet.

**Comment by robintw** [comment]
The new version with this additional feature has now been released.

@re4lfl0w if you run `pip install -U recipy` you should find it all works. Let us know if you have any more problems.
