### ISSUE TITLE
GUI port number consistency

### ISSUE THREAD

**Issue by sjdenny** [recipy/recipy#80]
I'm currently giving recipy a test-drive, and I'm liking it so far.  Often I have several browser windows open, so it's a bit random at present which window opens up the GUI.  I can then open it up in the window I actually want it, but because the port is random I have to go back to the terminal to see which port was allocated.

Compare this with my Jupyter workflow, where the port is predictable, I have a bookmark on my browser and can reach it immediately without needing to check the output on the command line.  Maybe it's just me, but a fixed port could make this more slick.  Happy to make a PR about this, thoughts?

**Comment by robintw** [comment]
Good point, thanks for raising this.

I seem to remember that there was a reason for using a random port, but I can't remember what it was. Can you remember @jvdzwaan?

**Comment by sjdenny** [comment]
The only potential issue I see is if port 9000 (say) is already taken, so we try 9001, if that's taken, try 9002, and so on.  After a fixed number of failures it could fall back to a random port.  If the user doesn't like the default port, this could be a parameter in an rc file.

**Comment by jvdzwaan** [comment]
@sjdenny: that was the behaviour I wanted too, but it is not that simple in Flask. It now randomly finds an unused port, which ensures the port is not taken, but perhaps the strategy described in this stackoverflow question works. 

http://stackoverflow.com/questions/5085656/how-to-get-the-current-port-number-in-flask

I'll have a look at it later.

**Comment by robintw** [comment]
I also like the idea of being able to configure the port in the configuration file. Something "port = 1234" in the [general] section sounds good to me.
Sent from my phone, please excuse brevity and/or mistakes
On 9 Sep 2015 8:46 am, Janneke van der Zwaan <notifications@github.com> wrote:@sjdenny: that was the behaviour I wanted too, but it is not that simple in Flask. It now randomly finds an unused port, which ensures the port is not taken, but perhaps the strategy described in this stackoverflow question works. 

http://stackoverflow.com/questions/5085656/how-to-get-the-current-port-number-in-flask

I'll have a look at it later.
