### ISSUE TITLE
Store versions of libraries used

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#87]
As each library is patched, store its version number, and collect those into the metadata.

**Comment by ryanpepper** [comment]
I think a very simple thing to do would be to simply, after import of a package call "packagename.version.version" as this works for a number of common packages (numpy, scipy, pandas).

**Comment by robintw** [comment]
I agree, possibly trying a few other standard ways to get the version (`__version__` for example) as well if that doesn't work. They could then stored as a list of tuples in the recipy metadata:

`[ ('numpy', '1.6.0'), ('pandas', '0.6.7')...]`

**Comment by ryanpepper** [comment]
Hi Robin,
Ian Hawke showed me an iPython magic called Watermark that sort of does this - it gives you some details about your environment (x86 or x64, Operating system version, etc) and it can get the package versions too. It's also GPLv3. This might help in implementing this:
https://github.com/rasbt/watermark

**Comment by robintw** [comment]
This is implemented now.
