### ISSUE TITLE
Recipy not able to find a file 

### ISSUE THREAD

**Issue by ritviksahajpal** [recipy/recipy#89]
![recipy](https://cloud.githubusercontent.com/assets/2277375/10313490/e19c724e-6c1d-11e5-9b5d-dbea53692ff6.png)

Used recipy for a python run, while the recipy gui shows a file being created (cc_NDVI.png), searching for it through command line does not find the file (see screenshot). Is there something I should be doing differently?

**Comment by robintw** [comment]
I think you're running into a path issue: by default, `recipy` currently searches for a file in the current folder. If you change to the folder where `cc_NDVI.png` is located then it should work.

Alternatively, you can run `recipy search --fuzzy cc_NDVI.png` which should find it regardless what folder you're in.

(I'm aware this is significantly less than ideal, but it should be solved with some new features I'm in the process of adding).

**Comment by ritviksahajpal** [comment]
Thanks, --fuzzy helps a lot!

**Comment by robintw** [comment]
Sorry, I've only just seen your update on this comment (for some reason Github didn't notify me about it). Are you still having problems with `--fuzzy` then?

**Comment by robintw** [comment]
File searching has been completely reworked for the next version of recipy, due to be released very soon - so I'm closing this issue as I'm 99% sure that this is fixed.
