### ISSUE TITLE
Sort out correct precedence issues for CLI arguments

### ISSUE THREAD

**Issue by robintw** [recipy/recipy#99]
We give a single 'identifier' of some sort. That could be a file to be hashed, a file-path to be searched for as a string, a hash, a run ID, or a fuzzy search for some of the above.

The current interface for choosing which one to search for is rather complicated and not fully logical - this needs fixing.

**Comment by bilderbuchi** [comment]
With argparse from the stdlib you can build pretty detailed and powerful CLIs, and its pretty easy to compose the necessary code, default values, etc.

**Comment by robintw** [comment]
I think this is sorted with the new `-p` option and changing the default to be searching by hash, so I'll close for the moment and we can re-open if users have issues.
